#!/bin/sh
PRG="$(basename $0)"
test "$PRG" = "wrap" && { PRG=$1; shift; }
PATH=/opt/ipnb/bin:$PATH LD_LIBRARY_PATH=/opt/rh/python27/root/usr/lib64${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH} exec "/opt/ipnb/bin/${PRG}" "$@"
