*** Makefile.orig	2019-06-10 22:33:19.000000000 +0000
--- Makefile	2020-01-19 20:57:33.808431823 +0000
***************
*** 137,149 ****
  JARS+=$(GROUPING_JAR)           # grouping module
  JARS+=$(HIGHLIGHTER_JAR)        # highlighter module, needs memory contrib
  JARS+=$(JOIN_JAR)               # join module
! JARS+=$(KUROMOJI_JAR)           # japanese analyzer module
  #JARS+=$(LUKE_JAR)               # luke
  JARS+=$(MEMORY_JAR)             # single-document memory index
  JARS+=$(MISC_JAR)               # misc
! JARS+=$(MORFOLOGIK_JAR)         # morfologik analyzer module
! JARS+=$(NORI_JAR)               # korean analyzer module
! #JARS+=$(PHONETIC_JAR)           # phonetic analyzer module
  JARS+=$(QUERIES_JAR)            # regex and other contrib queries
  JARS+=$(QUERYPARSER_JAR)        # query parsers
  JARS+=$(SANDBOX_JAR)            # needed by query parser
--- 137,149 ----
  JARS+=$(GROUPING_JAR)           # grouping module
  JARS+=$(HIGHLIGHTER_JAR)        # highlighter module, needs memory contrib
  JARS+=$(JOIN_JAR)               # join module
! #JARS+=$(KUROMOJI_JAR)           # japanese analyzer module
  #JARS+=$(LUKE_JAR)               # luke
  JARS+=$(MEMORY_JAR)             # single-document memory index
  JARS+=$(MISC_JAR)               # misc
! #JARS+=$(MORFOLOGIK_JAR)         # morfologik analyzer module
! #JARS+=$(NORI_JAR)               # korean analyzer module
! JARS+=$(PHONETIC_JAR)           # phonetic analyzer module
  JARS+=$(QUERIES_JAR)            # regex and other contrib queries
  JARS+=$(QUERYPARSER_JAR)        # query parsers
  JARS+=$(SANDBOX_JAR)            # needed by query parser
***************
*** 177,182 ****
--- 177,183 ----
  HIGHLIGHTER_JAR=$(LUCENE)/build/highlighter/lucene-highlighter-$(LUCENE_VER).jar
  JOIN_JAR=$(LUCENE)/build/join/lucene-join-$(LUCENE_VER).jar
  KUROMOJI_JAR=$(LUCENE)/build/analysis/kuromoji/lucene-analyzers-kuromoji-$(LUCENE_VER).jar
+ PHONETIC_JAR=$(LUCENE)/build/analysis/phonetic/lucene-analyzers-phonetic-$(LUCENE_VER).jar
  LUKE_JAR=$(LUCENE)/build/luke/lucene-luke-$(LUCENE_VER).jar
  MEMORY_JAR=$(LUCENE)/build/memory/lucene-memory-$(LUCENE_VER).jar
  MISC_JAR=$(LUCENE)/build/misc/lucene-misc-$(LUCENE_VER).jar
***************
*** 195,200 ****
--- 196,202 ----
  ASM_JAR=$(LUCENE)/expressions/lib/asm-5.1.jar
  ASM_COMMONS_JAR=$(LUCENE)/expressions/lib/asm-commons-5.1.jar
  HPPC_JAR=$(LUCENE)/facet/lib/hppc-0.8.1.jar
+ APACHE_COMMONS_CODECS_JAR=$(LUCENE)/analysis/phonetic/lib/commons-codec-1.11.jar
  LOG4J_API_JAR=$(LUCENE)/luke/lib/log4j-api-2.11.2.jar
  LOG4J_CORE_JAR=$(LUCENE)/luke/lib/log4j-core-2.11.2.jar
  
***************
*** 290,295 ****
--- 292,300 ----
  $(MORFOLOGIK_JAR): $(LUCENE_JAR)
  	cd $(LUCENE)/analysis/morfologik; $(ANT) -Dversion=$(LUCENE_VER)
  
+ $(PHONETIC_JAR): $(LUCENE_JAR)
+ 	cd $(LUCENE)/analysis/phonetic; $(ANT) -Dversion=$(LUCENE_VER)
+ 
  $(MISC_JAR): $(LUCENE_JAR)
  	cd $(LUCENE)/misc; $(ANT) -Dversion=$(LUCENE_VER)
  
***************
*** 336,341 ****
--- 341,347 ----
  
  GENERATE=$(JCC) $(foreach jar,$(JARS),--jar $(jar)) \
             $(JCCFLAGS) --use_full_names \
+            --include $(APACHE_COMMONS_CODECS_JAR) \
             --include $(ANTLR_JAR) \
             --include $(ASM_JAR) \
             --include $(ASM_COMMONS_JAR) \
